apiVersion: v1
kind: Secret
metadata:
  name: linkedin-secrets
  namespace: default
type: Opaque
stringData:
  linkedin_user: "<your_linkedin_user>"
  linkedin_pass: "<your_linkedin_pass>"
  database_url: "<your_database_url>"
